### ISSUE TITLE
Warning: assert(): SPARQL query failed

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#109]
I was just getting
```
Warning: assert(): SPARQL query failed: SELECT ?q (count(?article) as ?count) WHERE { SELECT ?q ?article WHERE { VALUES ?q { } . ?article wdt:P50 ?q . } } group by ?q #TOOL: legacy code failed in /data/project/author-disambiguator/public_html/magnustools/ToolforgeCommon.php on line 427
```

for https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=ASDEX%20Upgrade%20Team , 
which otherwise worked as expected (see output in https://tools.wmflabs.org/quickstatements/#/batch/24402 and https://tools.wmflabs.org/scholia/organization/Q79426724 ).

This seems to be the same error that was behind #42 , but the underlying SPARQL query was different back then.

**Comment by Daniel-Mietchen** [comment]
Getting the same error for 
https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Qingwei%20Yang .

**Comment by Daniel-Mietchen** [comment]
Getting it for lots of other search strings as well, but not for all, e.g. not for 
https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Viness%20Pillay .

**Comment by Daniel-Mietchen** [comment]
Here is a screenshot for yet another case, 
https://tools.wmflabs.org/author-disambiguator/?fuzzy=0&wbsearch=0&limit=500&name=Elizabeth+Tildesley .

![Screenshot_2019-12-22 Author Disambiguator(2)](https://user-images.githubusercontent.com/465923/71330539-9c8b7d80-24fb-11ea-8bcf-b92989050840.png)

**Comment by Daniel-Mietchen** [comment]
Actually, the QuickStatements batch mentioned in the first comment on this thread did not behave normally - it did not finish, even upon multiple "Fix errors" retries, and it made repeated edits to the same item, e.g. as per https://www.wikidata.org/w/index.php?title=Q48194357&action=history .

**Comment by arthurpsmith** [comment]
This will happen if the query server is not behaving properly in some way. I don't think there's really anything on the author disambiguator side to do about it; the error display is even coming from a library I copied from Magnus Manske, so not really my code at all. I assume his tools would have exactly the same problem (as suggested by QuickStatements having problems here also). Anyway, these will crop up if WDQS is down in some way, but otherwise don't seem to be a problem... closing.
