### ISSUE TITLE
Handle unordered authors correctly! (was: Batches show as complete but no changes made to items)

### ISSUE THREAD

**Issue by davidhicks** [arthurpsmith/author-disambiguator#110]
See batches https://tools.wmflabs.org/author-disambiguator/batches_oauth.php?id=3496c5 and https://tools.wmflabs.org/author-disambiguator/batches_oauth.php?id=a64ec9 which should have resulted in dozens of items having a P50 claim added, but this not occur despite no errors appearing, and the batches showing as complete/done.

**Comment by arthurpsmith** [comment]
@davidhicks that's weird, the Wikibase API should have returned an error if they didn't actually update, but I see no sign of it. I have reset both of these batches so all the changes are listed as "READY" rather than "DONE"; can you try restarting them (go to your "Batches" page - batches_oauth.php without the id) and click on restart, and let me know if that works?

**Comment by arthurpsmith** [comment]
@davidhicks do you have any further information on this, has it happened again?

**Comment by davidhicks** [comment]
@arthurpsmith I just tried restarting both jobs and they now completed successfully, as expected. Thanks for resetting the batches.

**Comment by davidhicks** [comment]
@arthurpsmith I just tried a new batch at https://tools.wmflabs.org/author-disambiguator/batches_oauth.php?id=854d78 and ran into the same problem. The batch is marked as complete but no edits occurred.

**Comment by arthurpsmith** [comment]
That is so strange. The Wikidata API must be returning a success indicator even though the edit didn't succeed?? Looking into it...

**Comment by arthurpsmith** [comment]
Oh! The problem is these articles don't have ordinal numbers attached to the author name strings (author 1, 2, 3, etc.), and I'm identifying which author to replace by that ordinal number. So it's getting a "success" response because it's not changing anything... This really should work in this case too, hmm.

**Comment by arthurpsmith** [comment]
Ok, I can't think of an easy way to fix this with the current design; I've instead added an error response when it finds unordered authors, so at least it won't look like it's doing something when it's not. Hopefully I can get back to this with a better solution later. In the meantime, I think the non-oauth version should allow these updates (via Quickstatements) - right?

**Comment by arthurpsmith** [comment]
fixing this basically looks like it requires moving from my original "ArticleModel" to "ArticleModel2" that describes the author list more completely, and which has been used for a while for the work item and author item pages; unfortunately that means rewriting all the associated clustering components to use the new model.

**Comment by arthurpsmith** [comment]
I've made the switch in the latest version live on the server! In particular I did the matching for all the Joyce K. Reynolds RFC items, it seems to be working. So this general issue of not handling un-ordered authors should now be fixed. The specific batches mentioned here can't be fixed though, you'll have to create new ones for anything not already completed.

**Comment by davidhicks** [comment]
Thanks @arthurpsmith 

Tried a new test batch at https://author-disambiguator.toolforge.org/batches_oauth.php?id=c5519dd8 and seems to be working properly :)
