### ISSUE TITLE
Disambiguation for works by Evren Sirin

### ISSUE THREAD

**Issue by WolfgangFahl** [arthurpsmith/author-disambiguator#169]
Trying to disambiguate [Evren Sirin ](https://www.wikidata.org/entity/Q111620956) as a author name doesn't seem to work properly.

First i started from https://scholia.toolforge.org/author/Q111620956 clicking "Improve data". 

Later I tried the following SPARQL query:

```sparql
SELECT ?work ?workLabel
WHERE {
  VALUES  ?author_name {
     "Evren Sirin"
  }    
  OPTIONAL { ?work wdt:P2093 ?author_name. }
  ?work rdfs:label ?workLabel.
}
```
[try it!](https://query.wikidata.org/#%0A%0ASELECT%20%3Fwork%20%3FworkLabel%0AWHERE%20%7B%0A%20%20VALUES%20%20%3Fauthor_name%20%7B%0A%20%20%20%20%20%22Evren%20Sirin%22%0A%20%20%7D%20%20%20%20%0A%20%20OPTIONAL%20%7B%20%3Fwork%20wdt%3AP2093%20%3Fauthor_name.%20%7D%0A%20%20%3Fwork%20rdfs%3Alabel%20%3FworkLabel.%0A%7D%0A)

**Comment by WolfgangFahl** [comment]
The reason for the behavior seems to be the delay until

https://author-disambiguator.toolforge.org/names_oauth.php?doit=Look+for+author&name=Evren%20Sirin

shows up. May be this is avoidable by being able to enter the author name directly instead of relying to be able to query it?

**Comment by arthurpsmith** [comment]
Hi @WolfgangFahl - I'm not sure I understand what you saw as a problem. When I go to the Scholia page you mention and click "Improve data" the link you for this tool appears immediately under the "Author name strings to be resolved" heading. Maybe an issue with your browser or internet connection? Once you are on the author disambiguator page you can always enter another name on the "Author name" line at the top and search for that right away. Sometimes for example you may want to look for a variation of the name, such as with a middle initial (SPARQL searching is very literal about string matching). Also "Fuzzy match" may be useful if the author sometimes just goes by their first initial instead of first name. Anyway, let me know if there's anything concrete that you think needs to be done further here.

**Comment by WolfgangFahl** [comment]
@arthurpsmith  - the problem showed up a few seconds after i had created the  item https://www.wikidata.org/entity/Q111620956 - since the blazegraph infrastructure has a delay the queries used by scholia didn't included the author yet although the dataset itself was already their. This led to the peculiar followup problem i was seeing. Being able to enter the author name string would be safe even if the author item record has not been updated yet and a selection of papers would be possible for human review e.g. as a basis to decide whether it's worthwhile to create a separate author item in the first place.

**Comment by arthurpsmith** [comment]
Ok, this sounds like a problem on the Scholia end then. You can always query directly on the author-disambiguator page for any name string you like. I'm going to close this here, but you may want to raise it over there.
