### ISSUE TITLE
Add an option to (pre) filter by way of a SPARQL query

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#17]
Mostly useful for those cases which give lots of results when unfiltered (see e.g. #9 ), but can also be useful for smaller  sets.

**Comment by Daniel-Mietchen** [comment]
I just tried to implement a demo using Listeria but got stuck halfway in (query works, but list doesn't): https://www.wikidata.org/wiki/Wikidata:WikiProject_Source_MetaData/Wikidata_lists/Semi-disambiguated_authors .

**Comment by arthurpsmith** [comment]
So currently technically the code is doing several queries: (1) for people with the provided name(s) (the list of possible matching authors), and (2) for articles with author name strings matching the provided name(s) (and then some supplemental lookups to fill in details). Assuming we are sticking with matching 1 author at a time for now, I would guess what you're suggesting here would be a modification of query (2) - i.e. additional filters on the article match, but we'd still need to have the SPARQL also filter on author name string. I'll think about this a bit - rather than SPARQL maybe a form for additional filter terms (journal, other authors, ??) would be helpful?

**Comment by Daniel-Mietchen** [comment]
I now have that list going - the list is built based on a SPARQL query, and the last column in the list is pointing to the disambiguator. Would be great to feed such queries into the disambiguator directly and to use it as a filter on the lookup results.

**Comment by Daniel-Mietchen** [comment]
Other scenarios for such pre-filtering would be by topic, e.g. for [author name strings commonly find on Zika papers](https://query.wikidata.org/#select%20%3Fshort_author%20%28count%28%3Fpaper%29%20as%20%3Fcount%29%20where%20%7B%0A%20%20%7B%20%3Fpaper%20wdt%3AP921%20wd%3AQ202864%20.%20%7D%20UNION%20%7B%20%3Fpaper%20wdt%3AP921%20wd%3AQ8071861%20.%20%7D%0A%20%20%3Fpaper%20wdt%3AP2093%20%3Fshort_author%20.%0A%20%20%7D%0Agroup%20by%20%3Fshort_author%0Aorder%20by%20desc%28%3Fcount%29).

**Comment by arthurpsmith** [comment]
This actually wasn't too hard to add - rather than a full SPARQL query, what it takes as input is additional predicate/object pairs separated by semicolons (actually you could probably do more than that too, but I haven't really experimented much). Filter by topic, coauthor name or coauthor wikidata ID works fine. Check it out!

**Comment by Daniel-Mietchen** [comment]
Thanks! I'm making good use of this now, e.g. at https://www.wikidata.org/wiki/Wikidata:University_of_Virginia/Listeria/UVa_people/Author_name_strings_matched_to_UVa_people_items_using_Stated_As .
