### ISSUE TITLE
Leading white space leads to 400 error

### ISSUE THREAD

**Issue by VDK** [arthurpsmith/author-disambiguator#183]
I get a 400 error page when the "author name" field is filled with a string that has a tab as the leading white space 
* [this is a 400 error](https://author-disambiguator.toolforge.org/?name=%09Luc+J.+Teppema&doit=Look+for+author&limit=5&filter=)

**Comment by arthurpsmith** [comment]
Ooh, thanks for finding this, definitely needs fixing.

**Comment by arthurpsmith** [comment]
Hmm, actually this is a general problem with the lighttpd server - the backend web server this is all running on (via kubernetes this service runs in one of a limited set of allowed containers on toolforge). It was updated in the past month or so to a new version that does not allow certain control characters - including the tab character - in GET url's. So the server is intercepting this request before it even gets to any of the author-disambiguator code. I think the only way to fix this is to replace the form so it is using "POST" instead of "GET" - which isn't a big deal but it makes the URL no longer something that can be easily shared.

**Comment by arthurpsmith** [comment]
@VDK ok this problem should be fixed now, let me know if you are still seeing issues!
