### ISSUE TITLE
For authors with lots of papers to reconcile, the conversion to QuickStatements does not work

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#23]
E.g. for https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=PLOS%20ONE%20Staff .

In similar cases before, I could work around by just including one of the groups suggested by the tool, but here, it suggests only one group (which makes sense), and while I suppose I could click away manually a certain number of those tick boxes, I don't know what number that would need to be, and I do not want to try to find out manually.

One solution is likely to increase memory (just like in #9), another would be pre-filtering, as per #17, and yet another would be to limit batches to a certain number of publications at a time, as suggested in option 1 in [this comment](https://github.com/arthurpsmith/author-disambiguator/issues/9#issuecomment-442520670) in #9.

**Comment by arthurpsmith** [comment]
Are you actually seeing an out of memory error? I'm thinking the problem in this case might be that Q59773600 is not an instance of Q5 - but we should allow for collective authors. At least I'll try fixing that and then see if that's still the problem...

**Comment by arthurpsmith** [comment]
Hmm, actually looks like a PHP limitation - no more than 1000 fields can be set in a form. I think I'll limit it to, lets say, 900 papers at a time?

**Comment by arthurpsmith** [comment]
Ok, I believe this is fixed - also the other out-of-memory issue, at least via this mechanism!

**Comment by Daniel-Mietchen** [comment]
Here's another one that does not convert for me: https://tools.wmflabs.org/author-disambiguator/?name=Sandra+S+Padula&doit=Look+for+author&filter=

**Comment by arthurpsmith** [comment]
Checking this out again... maybe the limit needs to be lower?

**Comment by arthurpsmith** [comment]
Hmm, it's not a lot of papers actually - I see only 4. I assume the problem here is the large number of authors (2000+ on each listed paper)?

**Comment by Daniel-Mietchen** [comment]
Another case here: https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Lin%20H%20Chen , even if filtered to https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&filter=wdt%3AP921+wd%3AQ202864&name=Lin%20H%20Chen&filter=wdt%3AP2093+%22Lin%20H%20Chen%22

**Comment by arthurpsmith** [comment]
Hi Daniel - I regrouped some of the code to skip most of the memory/time-intensive stuff when generating the Quickstatements commands, I think this will deal with most of the problem you've seen here. However, there's definitely still a memory use problem associated with large quantities of fetched data, I need to find a better way to handle that.

**Comment by arthurpsmith** [comment]
Ok, I did some checks based on Sandra S Padula and it looks like each article that's fetched is using multiple megabytes - maybe as much as 10 - but those are mostly papers with 2000+ authors! Also, it appears the query method it is using (from Magnus' wikidatatools php library) sometimes does NOT return anything for a valid QID - again I'm guessing because of some data size limitation. I think what I need to do is replace the use of wikidatatools with a new library probably using SPARQL, just to fetch the things actually needed. This may take a bit of work...

**Comment by arthurpsmith** [comment]
For now I've limited the fetch to 100 articles (instead of 900) which should also make the page more manageable even for less data-heavy articles.

**Comment by arthurpsmith** [comment]
I believe this is now (mostly?) fixed through two modifications: (1) using SPARQL to fetch article data, rather than the wikidata API, and (2) allowing the user to limit the number of articles fetched (default is back to 500). However, Quickstatements itself seems to have trouble with some of those multi-thousand-author papers, so we may continue to have issues here. And I'm not certain I've handled all the problems associated with this. But I think this can close for now.
