### ISSUE TITLE
"Potential author items" section is missing for author with many many-author papers

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#27]
example: https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=Stephen%20J%20Chanock

**Comment by arthurpsmith** [comment]
The section is there, it just has no matching authors! If you enter "Stephen J. Chanock" as the name, it does find him - this is related to #18 but obviously a problem in cases like this even without the "fuzzy" criterion. As a side note, do you know if it's a PubMed thing that they seem to remove the '.' from initials? We have many many papers with that issue.

**Comment by arthurpsmith** [comment]
I've reworked the name search so that now "Stephen J. Chanock" or "Stephen J Chanock" entered would match either string, and "Stephen James Chanock" would also match both of those as well as the full string. I think this is much improved now, so closing, but we should open a new issue with any new examples that don't work as expected!
