### ISSUE TITLE
Middle name strings are automatically shortened

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#34]
Currently,
https://tools.wmflabs.org/author-disambiguator/?doit=Look+for+author&name=International%20Commission%20On%20Zoological%20Nomenclature
can not be used to generate QuickStatements to link the papers to Q1071346, 
and the suggested string for the ORCID part creates shortened "middle names" C O Z as well,
presumably due to https://github.com/arthurpsmith/author-disambiguator/commit/7690d3de0e100224610b28fdd24d1580ef42222c .

**Comment by Daniel-Mietchen** [comment]
For the record, this worked fine earlier today, as per https://tools.wmflabs.org/quickstatements/#/batch/6786 and https://tools.wmflabs.org/quickstatements/#/batch/6779 .

**Comment by arthurpsmith** [comment]
Oops - problem was $name variable was reused. I've fixed this issue.
However, the name search is another matter - I switched it to be much more specific and using SPARQL directly to find entries by name, but that means it's now case sensitive. That's usually fine if you cut and paste names from a proper source (or a Wikidata item). In this case the problem was the label in Wikidata is "International Commission on Zoological Nomenclature" - with a lowercase 'on'. I don't really want to go back to the other (case-insensitive) search method as you can't filter by class and it was returning every matching paper as well as the potential authors, way too much information. Unless you think the case sensitivity is a serious problem I think that's all we can do for now...

**Comment by Daniel-Mietchen** [comment]
Thanks! Making it case sensitive makes sense, but the problem was that even though I had supplied the QID, the QS statements were not generated.

Works fine now, and the batch is underway at https://tools.wmflabs.org/quickstatements/#/batch/6805 .
