### ISSUE TITLE
Build a variant that helps disambiguate authors of a single publication

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#67]
Here, I am thinking of something like 
https://tools.wmflabs.org/author-disambiguator/?fuzzy=0&limit=1&name=Li%20Li
but instead of the **name** parameter, it would be called via a **work** parameter that expects the QID of a given work (optionally via DOI/ PMID/ PMCID/ arXiv ID etc., e.g. by using the Wikidata Hub).

This would address the same problem as #66 but should be more straightforward to implement.

**Comment by arthurpsmith** [comment]
The idea being, you start from that publication and the links from the author name strings would go to name pages for those names? I'll have to think about it, but in principle I think it makes sense... I'm afraid I've been a bit busy with other priorities but I do plan to get back to updating this tool in the next week or two...

**Comment by Daniel-Mietchen** [comment]
Yes, the key idea is to have a page for one work which ideally lists all author name strings for that work and links them to the corresponding ``name`` pages.

This would look very similar to the example given above, with the main difference being that right now, the ``limit=1`` part does not give the user control over which work to display (for me, it's https://www.wikidata.org/wiki/Q21131061 right now), whereas the new mechanism would allow to specify something like ``&work=Q21131061`` or similar.

**Comment by arthurpsmith** [comment]
Ok, there's a new "work_item.php" page - for example here:
https://tools.wmflabs.org/author-disambiguator/work_item.php?id=Q27335792&doit=Get+author+links+for+work

I should probably link it from other pages. Any suggestions on what else should be done with it?

**Comment by Daniel-Mietchen** [comment]
I had a first go at it from your example, which led to
https://tools.wmflabs.org/quickstatements/#/batch/16968
and thus
https://tools.wmflabs.org/scholia/author/Q66317808 .

Yes, cross-linking would be useful.

Will test a bit more later.

**Comment by Daniel-Mietchen** [comment]
Things to add to work_item.php:
- published in (with link to associated Scholia missing page)
- main subject (with link to associated Scholia missing page)
- perhaps links to author_item.php for citing/ cited papers

Links to work_item.php from pages like 
- https://tools.wmflabs.org/author-disambiguator/author_item.php?limit=50&id=Q54958038
- https://tools.wmflabs.org/author-disambiguator/index.php?limit=50&name=K.+Romanowska-Rybinska

**Comment by arthurpsmith** [comment]
Ok, "published in" and "main subject" links have been added, with the Scholia links as suggested. Also links from index.php and author_item etc. to the "work_item" page via a [work] link after the title - do you think that's sufficient? Maybe it should be highlighted somehow?

I'm not sure what you mean by links to author_item for citing/cited papers - you mean if we have identified authors on any citing or cited papers to add a list to the work item page? I haven't looked at traversing the citation graph at all here yet...

**Comment by Daniel-Mietchen** [comment]
I just tried to move the [work] link to the author column, as per https://github.com/arthurpsmith/author-disambiguator/pull/72 .

Some highlighting seems useful &mdash; perhaps rethink the color scheme altogether, e.g. why is the journal linked in black, the topic in red?

Regarding the citation graph, what I had in mind here is that people often cite their own work, so if we already have a work with a P50 statement that cites our target work and the target work has a P2093 string that is in the label or aliases of that person's item, then that could be suggested on the page as a potential match. Such citation graph walking is very helpful in cases like your example where the author name strings are provided just with initials.

**Comment by arthurpsmith** [comment]
I don't admit to any graphic design expertise or skill (or much knowledge of CSS/Javascript...) so any suggestions you have on colors - or somebody else to advise on it - are welcome!

I think what you're suggesting is to have the work page allow for some suggested matches; I think that's an interesting way to go but there's a lot to consider about how to do that. In addition to citations, there's co-authorship relations (i.e. a person with a matching name who is coauthor of one of the identified authors on this paper). There are also issues with multiple P2093 statements that aren't working right now - for example this paper:
https://tools.wmflabs.org/author-disambiguator/work_item.php?id=Q31123705

If you look at the Wikidata page you can see every author is duplicated (due to a merge as the article had been added twice) but right now it's only showing one version of each author - so I think there should be some way of showing and addressing that.

Also there are some papers I've run across (very rare) that had problems with author numbering - like having one author accidentally repeated in the middle - when there are 100's of authors that becomes an awfully lot of work to manually re-number every author, so perhaps this page could help with that task also.

I think I'll add some of these as issues here...

**Comment by arthurpsmith** [comment]
Hi Daniel - assuming the OAuth consumer gets approved, you should be able to see new features for merging, renumbering, and matching of authors when you click on the new link "Log in to your Wikimedia account to use OAuth instead of Quickstatements for updates - still experimental." - the directly link can be generated by replacing "work_item.php" with "work_item_oauth.php". It updates the work directly rather than going through Quickstatements, so should be much faster and easier on the WDQS updates as well (making a single "udpate" rather than potentially hundreds of individual edits).

**Comment by arthurpsmith** [comment]
OAuth was approved, you should be able to do this now!

**Comment by Daniel-Mietchen** [comment]
I saw the changes, tested them and like them. Nice improvements overall, and inspiration for next steps. Will play around a bit further and then get back here with new suggestions.

**Comment by arthurpsmith** [comment]
Further suggestions on new issues? I think this can close...
