### ISSUE TITLE
Small enhancement to fuzzy searches of Polish names

### ISSUE THREAD

**Issue by Kpjas** [arthurpsmith/author-disambiguator#85]
It seems that there is a peculiar irregularity in published scientific papers in naming practice  of a certain type of Polish names.
Let's take a female Polish researcher **Zofia Rogóź** as an example.

Sometimes 'ó' is left as is and other diacritics are transcribed so the author string becomes **Zofia Rogóz**, **Rogóz Z** or the like.  
See: [https://www.wikidata.org/wiki/Q47711274](https://www.wikidata.org/wiki/Q47711274)

The current fuzzy search algorithm is not aware of this variant and this kind of author strings is missed.

**Comment by arthurpsmith** [comment]
Sorry to be slow looking at this, I was working on some other major changes (OAuth!).

Is this peculiar to the ó character, or might there be other characters with the same problem?

**Comment by arthurpsmith** [comment]
Hmm - it might be because ó is in Latin-1 while ź is not? That would be relatively straightforward to tackle I think.

**Comment by Daniel-Mietchen** [comment]
There are other problems with non-ASCII characters, e.g. a standard search (without the "Wikibase search" box ticked) for the author name string [Marzanna Łusiak-Szelachowska](https://tools.wmflabs.org/author-disambiguator/?name=Marzanna+%C5%81usiak-Szelachowska&doit=Look+for+author&limit=500&filter=) yields no results (presumably because the "Ł" is not properly handled), even though there are several such articles in Wikidata, e.g. as per 
https://tools.wmflabs.org/author-disambiguator/author_item.php?id=Q76447322
or
https://tools.wmflabs.org/author-disambiguator/?name=Jacques+Scheres&doit=Look+for+author&limit=500&filter=wdt%3AP2093+%22Marzanna+%C5%81usiak-Szelachowska%22

[Ticking the Wikibase search box](https://tools.wmflabs.org/author-disambiguator/?name=Marzanna+%C5%81usiak-Szelachowska&wbsearch=1&doit=Look+for+author&limit=500&filter=) gives a range of errors:

<code>
Notice: Trying to get property 'results' of non-object in /data/project/author-disambiguator/public_html/lib/name_model.php on line 318

Notice: Trying to get property 'bindings' of non-object in /data/project/author-disambiguator/public_html/lib/name_model.php on line 318

Warning: Invalid argument supplied for foreach() in /data/project/author-disambiguator/public_html/lib/name_model.php on line 319

Notice: Trying to get property 'results' of non-object in /data/project/author-disambiguator/public_html/lib/name_model.php on line 338

Notice: Trying to get property 'bindings' of non-object in /data/project/author-disambiguator/public_html/lib/name_model.php on line 338

Warning: Invalid argument supplied for foreach() in /data/project/author-disambiguator/public_html/lib/name_model.php on line 339
</code>

**Comment by arthurpsmith** [comment]
I've added a latin-1 filter similar to the "ASCII" filter I was already using; this seems to do the trick! The problems Daniel brought up here I think have been fixed for some time, since I switched to proper php multi-byte handling. Anyway, I think this is done... Closing
